library(data.table)
library(dplyr)
library(tidyverse)
pwread <- fread('household_power_consumption.txt',na.strings="?",colClasses = c('character','character','numeric','numeric','numeric','numeric','numeric','numeric','numeric'))
pwread$Date <- as.Date(pwread$Date,format="%d/%m/%Y")

d <- subset(pwread,Date >= as.Date("2007-2-1") & Date <= as.Date("2007-2-2"))
datetime <- paste(d$Date,d$Time)
datetime <- strptime(datetime,"%Y-%m-%d %H:%M:%S")
d <- d[,!c("Date","Time")]
d <- cbind(datetime,d)
d <- d %>% rename(DateTime=datetime)
par(mfrow=c(1,1))
plot(d$Sub_metering_1~d$DateTime,type="l",ylab="Energy sub metering",xlab="")
lines(d$Sub_metering_2~d$DateTime,lty=3,col="red")
lines(d$Sub_metering_3~d$DateTime,lty=3,col="blue")
legend("topright",legend=c("Sub metering 1","Sub metering 2","Sub metering 3"),col=c("black","red","blue"),lty=1)
dev.copy(png,"plot3.png", width=480, height=480)
dev.off()